# See docs: https://goreleaser.com
version: 2
project_name: terraform-provider-stile
release:
  github:
    owner: StileEducation
    name: terraform-provider-stile
  name_template: '{{.Tag}}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
  binary: '{{ .ProjectName }}_v{{ .Version }}'
binary_signs:
  - {}
